[%
    T = {
        configure_1                                = "IntranetUserJS: Session expiry notice",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "IntranetUserJS: Session expiry notice",
        configure_5                                = "Configuration",
        configure_6                                = "Timeout (seconds, matching timeout system preference, default 1800s):",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "&rsaquo; IntranetUserJS: Session expiry notice &rsaquo; View JS plugin",
    }
%]