[%
    T = {
        configure_1                                = "IntranetUserJS: Istunnon vanhentumisilmoitus",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        configure_4                                = "IntranetUserJS: Istunnon vanhentumisilmoitus",
        configure_5                                = "Asetukset",
        configure_6                                = "Vanhentumisaika (sekuntia, timeout-järjestelmäasetusta vastaava aika, oletus 1800s):",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "&rsaquo; IntranetUserJS: Istunnon vanhentumisilmoitus &rsaquo; Näytä JS-liitännäinen",
    }
%]