[%
    T = {
        configure_1                                = "IntranetUserJS: Session expiry notice -asetukset",
        configure_2                                = "Koti",
        configure_3                                = "Lisäosat",
        configure_4                                = "IntranetUserJS: Session expiry notice",
        configure_5                                = "Asetukset",
        configure_6                                = "Ilmoitusaika (sekuntia, timeout-järjestelmäasetusta vastaava aika, oletus 1800s):",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "&rsaquo; SessionExpiryNotice &rsaquo; Näytä JS-työkalu",
    }
%]