[%
    T = {
        configure_1                                = "IntranetUserJS: Meddelande om sessionsutgång",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "IntranetUserJS: Meddelande om sessionsutgång",
        configure_5                                = "Inställningar",
        configure_6                                = "Tidsgräns (sekunder, enligt systeminställningen för timeout, standard 1800s):",
        configure_7                                = "Uppdateringsstatus",
        configure_8                                = "Pluginet har aldrig uppdaterats.",
        viewjs_1                                   = "&rsaquo; IntranetUserJS: Meddelande om sessionsutgång &rsaquo; Visa JS-plugin",
    }
%]