[%
    T = {
        configure_1                                = "IntranetUserJS: Meddelande om sessionsutgång Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "IntranetUserJS: Meddelande om sessionsutgång",
        configure_5                                = "Konfiguration",
        configure_6                                = "Meddelandetid (sekunder, motsvarande timeout-systeminställning, standard 1800s):",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Pluginet har aldrig uppgraderats.",
        viewjs_1                                   = "&rsaquo; SessionExpiryNotice &rsaquo; Visa JS-verktyg",
    }
%]